apiVersion: v1
kind: Service
metadata:
  name: postgres-order
  namespace: bookstore
spec:
  selector:
    app: postgres-order
  ports:
    - name: pg
      port: 5431
      targetPort: 5431
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-order
  namespace: bookstore
spec:
  selector:
    matchLabels:
      app: postgres-order
  serviceName: postgres-order
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-order
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: order_service
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
          args: ["-p", "5431"]
          ports:
            - containerPort: 5431
              name: pg
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
