apiVersion: v1
kind: Service
metadata:
  name: postgres-author
  namespace: bookstore
spec:
  selector:
    app: postgres-author
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-author
  namespace: bookstore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres-author
  template:
    metadata:
      labels:
        app: postgres-author
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-author-secret
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
