apiVersion: v1
kind: Service
metadata:
  name: postgres-author
  namespace: bookstore
spec:
  selector:
    app: postgres-author
  ports:
    - name: pg
      port: 5433
      targetPort: 5433
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-author
  namespace: bookstore
spec:
  selector:
    matchLabels:
      app: postgres-author
  serviceName: postgres-author
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-author
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: author_service
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
          args: ["-p", "5433"]
          ports:
            - containerPort: 5433
              name: pg
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
