apiVersion: v1
kind: Service
metadata:
  name: postgres-author
  namespace: bookstore
  labels:
    app: postgres-author
spec:
  clusterIP: None
  selector:
    app: postgres-author
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-author
  namespace: bookstore
spec:
  serviceName: postgres-author
  replicas: 1
  selector:
    matchLabels:
      app: postgres-author
  template:
    metadata:
      labels:
        app: postgres-author
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-author-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "gp3"
        resources:
          requests:
            storage: 5Gi