apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: bookstore
spec:
  selector:
    app: discovery-server
  ports:
    - port: 8761
      targetPort: 8761
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: tienphatng237/discovery-server:v1
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: spring-common-env
                  key: SPRING_PROFILES_ACTIVE
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
