apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: bookstore
spec:
  selector:
    app: config-server
  ports:
    - port: 8888
      targetPort: 8888
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: tienphatng237/config-server:v1
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "native"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: spring-common-env
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
