apiVersion: v1
kind: Service
metadata:
  name: author-service
  namespace: bookstore
spec:
  selector:
    app: author-service
  ports:
    - port: 8085
      targetPort: 8085
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-service
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: author-service
  template:
    metadata:
      labels:
        app: author-service
    spec:
      containers:
        - name: author-service
          image: tienphatng237/author-service:v1
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: spring-common-env
                  key: SPRING_PROFILES_ACTIVE
