apiVersion: v1
kind: Service
metadata:
  name: author-service
  namespace: bookstore
spec:
  selector:
    app: author-service
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-service
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: author-service
  template:
    metadata:
      labels:
        app: author-service
    spec:
      containers:
        - name: author-service
          image: tienphatng237/author-service:v1
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: spring-common-env
                  key: SPRING_PROFILES_ACTIVE
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: spring-common-env
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: spring-common-env
                  key: CONFIG_SERVER
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://postgres-author:5432/authordb
            - name: SPRING_R2DBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-author-secret
                  key: POSTGRES_USER
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-author-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
