apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: bookstore
spec:
  selector:
    app: order-service
  ports:
    - port: 8082
      targetPort: 8082
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: tienphatng237/order-service:v1
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: spring-common-env
                  key: SPRING_PROFILES_ACTIVE
