apiVersion: v1
kind: Service
metadata:
  name: stock-check-service
  namespace: bookstore
spec:
  selector:
    app: stock-check-service
  ports:
    - port: 8083
      targetPort: 8083
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-check-service
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-check-service
  template:
    metadata:
      labels:
        app: stock-check-service
    spec:
      containers:
        - name: stock-check-service
          image: tienphatng237/stock-check-service:v1
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: spring-common-env
                  key: SPRING_PROFILES_ACTIVE
