apiVersion: v1
kind: Service
metadata:
  name: stock-check-service
  namespace: bookstore
spec:
  selector:
    app: stock-check-service
  ports:
    - port: 8083
      targetPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-check-service
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-check-service
  template:
    metadata:
      labels:
        app: stock-check-service
    spec:
      containers:
        - name: stock-check-service
          image: tienphatng237/stock-check-service:v1
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: spring-common-env
                  key: SPRING_PROFILES_ACTIVE
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: spring-common-env
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: spring-common-env
                  key: CONFIG_SERVER
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://postgres-stock-check:5432/stockdb
            - name: SPRING_R2DBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-stock-secret
                  key: POSTGRES_USER
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-stock-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
