apiVersion: v1
kind: Service
metadata:
  name: message-service
  namespace: bookstore
spec:
  selector:
    app: message-service
  ports:
    - port: 8084
      targetPort: 8084
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      containers:
        - name: message-service
          image: tienphatng237/message-service:v1
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: spring-common-env
                  key: SPRING_PROFILES_ACTIVE
