# ConfigMap for Spring Apps
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-common-env
  namespace: bookstore
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  EUREKA_SERVER: "http://discovery-server:8761/eureka/"
  CONFIG_SERVER: "http://config-server:8888/"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
  NEXT_PUBLIC_API_URL: "http://api-gateway:8080"

---

# Secret for Postgres Author
apiVersion: v1
kind: Secret
metadata:
  name: postgres-author-secret
  namespace: bookstore
type: Opaque
stringData:
  POSTGRES_DB: authordb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

---

# Secret for Postgres Message
apiVersion: v1
kind: Secret
metadata:
  name: postgres-message-secret
  namespace: bookstore
type: Opaque
stringData:
  POSTGRES_DB: messagedb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

---

# Secret for Postgres Order
apiVersion: v1
kind: Secret
metadata:
  name: postgres-order-secret
  namespace: bookstore
type: Opaque
stringData:
  POSTGRES_DB: orderdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

---

# Secret for Postgres Stock
apiVersion: v1
kind: Secret
metadata:
  name: postgres-stock-secret
  namespace: bookstore
type: Opaque
stringData:
  POSTGRES_DB: stockdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

---

# Secret for Mongo
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
  namespace: bookstore
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: password
