apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: bookstore
type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: password

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-common-env
  namespace: bookstore
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka"
  NEXT_PUBLIC_API_URL: "https://api.tienphatng237.it.com"
